### PR TITLE
Merge develop into master

### PR DESCRIPTION
**Pull request by zanechua**
Changes:
* Switch native implementations to comply with upstream package licensing
* Implement configurable hasher

### CODE REVIEW

**Comment by tbrent** [comment]
What are the units of the memory config var? KB? 16 * 1024 = 16 MB? Could be worth a clarification in the readme. The other config vars are relatively obvious, but this one isn't entirely obvious.

**Comment by zanechua** [comment]
They are in KiB actually. Yeah probably could be added to the README.

**Comment by tbrent** [comment]
Wouldn't 16 * 1000 be more appropriate as a default, then, representing 16
MiB?

**Comment by zanechua** [comment]
16 * 1000 represents 16MB not 16MiB.

**Pull request merged**
